openapi: '3.0.2'
info:
  title: OpenID Connect Provider API
  version: '1.0'
servers:
  - url: http://op.com:8000/v1
tags:
  - name: asd
  
paths:
  /health:
    get:
      description: "健康检查路由"
      responses:
        '200':
          description: OK
  /authorization:
    get:
      description: ''
      parameters: []
      responses:
        '200':
          description: OK