Application:
  Name: OpenIDProvider
  Host: op.com
  Port: 8000


MySQL:
  Address: localhost:3306
  UserName: root
  Password: 123456
  DBName: OIDC_OP

Redis:
  Address: localhost:6379
  Password: ""
  DBName: 0

Kafka:

JsonWebToken:
  #加密算法hmac + sha256
  header_alg: HS256
  #类型
  header_typ: JWT
  #签发者
  payload_iss: localhost:8000
  #主题
  payload_sub: 
  #接收者
  payload_aud: 
  #生效时间
  payload_nbf:
  #过期时间
  payload_exp:
  #签发时间
  payload_iat:
  #编号
  payload_jti:
  #密钥
  signature_secret_key: opjwt


