POST    http://localhost:8000/v1/insertUser
{
	"user_id": 5004,
	"user_uuid": "asdasd4",
	"user_nick_name": "高洋",
	"user_intro": "没什么好介绍的",
	"user_school": "xxx大学",
	"user_avatar": "asd",
	"user_name": "高洋",
	"user_sex": "男",
	"user_birthday": "w",
	"user_id_number": "asdasq1",
	"user_location": "asdasd",
	"user_telephone": "asdasd1",
	"user_password": "asdsad",
	"user_email": "asd1",
	"user_create": "1999-01-09 16:34:48",
	"user_edited": "1987-03-09 03:16:37",
	"user_state": "0",
	"user_delete": 0
}

###
GET http://localhost:8000/v1/health


###
GET  http://localhost:8000/v1/encode_jwt

###
POST http://localhost:8000/v1/decode_jwt

{
"jwt_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb2NhbGhvc3Q6ODAwMCIsInN1YiI6Ik9wZW5JRFByb3ZpZGVyIiwiYXVkIjoibG9jYWxob3N0OjgwODEiLCJuYmYiOjE2OTYwNDQ1NTcsImV4cCI6MTY5NjA0NDg1NywiaWF0IjoxNjk2MDQ0NTU3LCJqdGkiOiJKV1QgSUQgMSIsInNlc3Npb25fc3RhdGUiOiJzZXNzaW9uSUQifQ.pfbmoyuQeWVzwdKyc-8aXQAskypAJSllR1bZoPkbVRk"
}

###
POST http://localhost:8000/v1/verify_jwt

{
"jwt_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJsb2NhbGhvc3Q6ODAwMCIsInN1YiI6Ik9wZW5JRFByb3ZpZGVyIiwiYXVkIjoibG9jYWxob3N0OjgwODEiLCJuYmYiOjE2OTYwNDQ1NTcsImV4cCI6MTY5NjA0NDg1NywiaWF0IjoxNjk2MDQ0NTU3LCJqdGkiOiJKV1QgSUQgMSIsInNlc3Npb25fc3RhdGUiOiJzZXNzaW9uSUQifQ.pfbmoyuQeWVzwdKyc-8aXQAskypAJSllR1bZoPkbVRk"
}
