openapi: '3.0.2'
info:
  title: OpenID Connect Provider API
  version: '1.0'
servers:
  - url: http://localhost:8000
paths:
  /health:
    get:
      responses:
        '200':
          description: OK
